channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pytorch==2.5.0
  - torchvision==0.20
  - torchaudio==2.5.0
  - pytorch-cuda=12.4
  - hydra-core==1.3.2
  - wandb==0.18.5
  - tqdm==4.66.6
  - scipy==1.14.1
  - lz4==4.3.2